name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update and Install Software
        run: |
          sudo apt update
          sudo apt -y install libpng-dev build-essential cmake python3-pip python3-venv git autoconf gcc-arm-none-eabi pkg-config p7zip-full

      - name: Restore Python cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-hg-engine-venv-${{ hashFiles('requirements.txt') }}

      - name: Restore tool cache
        uses: actions/cache@v4
        with:
          path: |
            tools/ENCODE_IMG
            tools/adpcm-xq
            tools/armips
            tools/msgenc
            tools/ndstool
            tools/nitrogfx
            tools/ntrWavTool.py
            tools/o2narc
          key: ${{ runner.os }}-hg-engine-tools-${{ hashFiles('Makefile', 'tools/source/**') }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Build hg-engine Only
        run: |
          make -j$(nproc)

      - name: Upload My Custom Game File
        uses: actions/upload-artifact@v4
        with:
          name: my-custom-heartgold
          path: |
            *.nds
            build/output/*.nds
